apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: uu1i8ygfu-go 
  janus-idp.io/tekton: uu1i8ygfu-go
  backstage.io/kubernetes-id: uu1i8ygfu-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: uu1i8ygfu-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml