apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: uu1i8ygfu-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:fb5ba6e1b18f3f73c5df60dd4711460988139ed2@sha256:0c7662ad6fcf293aea4d3dd02fec388da05a7d8f8ac0b7e354c8bf837a6ca3d8
          name: container-image
